### PR TITLE
Oakley/76 fix crustal permutation

### LINKED ISSUE #76: Correct the rupture size calculation when building crustal ruptures
AS SRM Team 

We want the strategy to  consider the length of the whole rupture.

So that it produces more effective coarsening effects. NB Highlighted by discussion with Kevin.

**Done when:**
 - [ ] reproduce the current incorrect behaviour as a failing test. 
 - [ ] make code modification to pass the test

### PR DESCRIPTION
**Pull request by voj**
fixes #76 

The resolution was to write simple code that filters ruptures after all ruptures have been generated.

### CODE REVIEW

File: src/main/java/nz/cri/gns/NSHM/opensha/ruptures/RuptureThinning.java [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+     * @param ruptures a list of generated ruptures
+     * @param predicate a rupture predicate that indicates which ruptures to keep
+     * @return a new list of the filtered ruptures
+     */
+    public static List<ClusterRupture> filterRuptures(List<ClusterRupture> ruptures, Predicate<ClusterRupture> predicate) {
+        return ruptures.stream().filter(predicate).collect(Collectors.toList());
+    }
+
+    /**
+     * Returns a predicate that takes a ClusterRupture and returns true iff the rupture's size (in sections) is
```
Comment (chrisbc) [inline src/main/java/nz/cri/gns/NSHM/opensha/ruptures/RuptureThinning.java:31]: typo: "iff"

**Review by chrisbc — APPROVED** [review]
Hi @voj :100:  -  just found one small typo (see comment)
